project:
  type: website

website:
  title: "Tyler Taylor"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - Sandstone
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto